export const courseItems = [
  {
    id: 1,
    image: "/src/assets/images/Landing/LandingCourses/CourseImages/dotnet.jpg",
    title: "دوره جامع .net core صفر تا صد",
    description:
      "محبوب ترین کتابخانه ی جاوااسکریپت حل مساله به روش کدنویسی پیشرفته و تمیز؛ برای مسائل واقعی دنیای نرم افزار  محبوب ترین کتابخانه ی جاوااسکریپت محبوب ترین کتابخانه ی جاوااسکریپت حل مساله به روش کدنویسی پیشرفته و تمیز؛ محبوب ترین کتابخانه ی جاوااسکریپت حل مساله به روش کدنویسی پیشرفته و تمیز.",
    lessonsCount: 202,
    hour: 14,
    createdAt: "ا اذر 1402",
    teacherName: "دکتر بحرالعلوم",
    teacherJob: "برنامه نویسی تحت فرانت و بکند",
    teacherImage: "/src/assets/images/CourseDetails/Teachers/teacher.png",
    studentsCount: 256,
    price: 5000000,
    courseStatus: "در حال برگزاری",
    courseEndTime: "24 شهریور 1403",
  },
  {
    id: 2,
    image: "/src/assets/images/Landing/LandingCourses/CourseImages/html.jpg",
    title: "دوره جامع HTML 5 صفر تا صد",
    description:
      "محبوب ترین کتابخانه ی جاوااسکریپت حل مساله به روش کدنویسی پیشرفته و تمیز؛ برای مسائل واقعی دنیای نرم افزار  محبوب ترین کتابخانه ی جاوااسکریپت محبوب ترین کتابخانه ی جاوااسکریپت حل مساله به روش کدنویسی پیشرفته و تمیز؛ محبوب ترین کتابخانه ی جاوااسکریپت حل مساله به روش کدنویسی پیشرفته و تمیز.",
    lessonsCount: 202,
    hour: 14,
    createdAt: "ا اذر 1402",
    teacherName: "دکتر بحرالعلوم",
    teacherJob: "برنامه نویسی تحت فرانت و بکند",
    teacherImage: "/src/assets/images/CourseDetails/Teachers/teacher.png",
    studentsCount: 256,
    price: 5000000,
    courseStatus: "در حال برگزاری",
    courseEndTime: "24 شهریور 1403",
  },
  {
    id: 3,
    image: "/src/assets/images/Landing/LandingCourses/CourseImages/python.jpg",
    title: "دوره جامع pyton صفر تا صد",
    description:
      "محبوب ترین کتابخانه ی جاوااسکریپت حل مساله به روش کدنویسی پیشرفته و تمیز؛ برای مسائل واقعی دنیای نرم افزار  محبوب ترین کتابخانه ی جاوااسکریپت محبوب ترین کتابخانه ی جاوااسکریپت حل مساله به روش کدنویسی پیشرفته و تمیز؛ محبوب ترین کتابخانه ی جاوااسکریپت حل مساله به روش کدنویسی پیشرفته و تمیز.",
    lessonsCount: 202,
    hour: 14,
    createdAt: "ا اذر 1402",
    teacherName: "دکتر بحرالعلوم",
    teacherJob: "برنامه نویسی تحت فرانت و بکند",
    teacherImage: "/src/assets/images/CourseDetails/Teachers/teacher.png",
    studentsCount: 256,
    price: 5000000,
    courseEndTime: "24 شهریور 1403",
  },
  {
    id: 4,
    image: "/src/assets/images/Landing/LandingCourses/CourseImages/python.jpg",
    title: "دوره جامع pyton صفر تا صد",
    description:
      "محبوب ترین کتابخانه ی جاوااسکریپت حل مساله به روش کدنویسی پیشرفته و تمیز؛ برای مسائل واقعی دنیای نرم افزار  محبوب ترین کتابخانه ی جاوااسکریپت محبوب ترین کتابخانه ی جاوااسکریپت حل مساله به روش کدنویسی پیشرفته و تمیز؛ محبوب ترین کتابخانه ی جاوااسکریپت حل مساله به روش کدنویسی پیشرفته و تمیز.",
    lessonsCount: 202,
    hour: 14,
    createdAt: "ا اذر 1402",
    teacherName: "دکتر بحرالعلوم",
    teacherJob: "برنامه نویسی تحت فرانت و بکند",
    teacherImage: "/src/assets/images/CourseDetails/Teachers/teacher.png",
    studentsCount: 256,
    price: 5000000,
    courseEndTime: "24 شهریور 1403",
  },
  {
    id: 5,
    image: "/src/assets/images/Landing/LandingCourses/CourseImages/dotnet.jpg",
    title: "دوره جامع .net core صفر تا صد",
    description:
      "محبوب ترین کتابخانه ی جاوااسکریپت حل مساله به روش کدنویسی پیشرفته و تمیز؛ برای مسائل واقعی دنیای نرم افزار  محبوب ترین کتابخانه ی جاوااسکریپت محبوب ترین کتابخانه ی جاوااسکریپت حل مساله به روش کدنویسی پیشرفته و تمیز؛ محبوب ترین کتابخانه ی جاوااسکریپت حل مساله به روش کدنویسی پیشرفته و تمیز.",
    lessonsCount: 202,
    hour: 14,
    createdAt: "ا اذر 1402",
    teacherName: "دکتر بحرالعلوم",
    teacherJob: "برنامه نویسی تحت فرانت و بکند",
    teacherImage: "/src/assets/images/CourseDetails/Teachers/teacher.png",
    studentsCount: 256,
    price: 5000000,
    courseStatus: "در حال برگزاری",
    courseEndTime: "24 شهریور 1403",
  },
  {
    id: 6,
    image: "/src/assets/images/Landing/LandingCourses/CourseImages/react.jpg",
    title: "دوره جامع React JS صفر تا صد",
    description:
      "محبوب ترین کتابخانه ی جاوااسکریپت حل مساله به روش کدنویسی پیشرفته و تمیز؛ برای مسائل واقعی دنیای نرم افزار  محبوب ترین کتابخانه ی جاوااسکریپت محبوب ترین کتابخانه ی جاوااسکریپت حل مساله به روش کدنویسی پیشرفته و تمیز؛ محبوب ترین کتابخانه ی جاوااسکریپت حل مساله به روش کدنویسی پیشرفته و تمیز.",
    lessonsCount: 202,
    hour: 14,
    createdAt: "ا اذر 1402",
    teacherName: "دکتر بحرال",
    teacherJob: "برنامه نویسی تحت فرانت و بکند",
    teacherImage: "/src/assets/images/CourseDetails/Teachers/teacher.png",
    studentsCount: 256,
    price: 5000000,
    courseStatus: "در حال برگزاری",
    courseEndTime: "24 شهریور 1403",
  },
  {
    id: 7,
    image: "/src/assets/images/Landing/LandingCourses/CourseImages/dotnet.jpg",
    title: "دوره جامع .net core صفر تا صد",
    description:
      "محبوب ترین کتابخانه ی جاوااسکریپت حل مساله به روش کدنویسی پیشرفته و تمیز؛ برای مسائل واقعی دنیای نرم افزار  محبوب ترین کتابخانه ی جاوااسکریپت محبوب ترین کتابخانه ی جاوااسکریپت حل مساله به روش کدنویسی پیشرفته و تمیز؛ محبوب ترین کتابخانه ی جاوااسکریپت حل مساله به روش کدنویسی پیشرفته و تمیز.",
    lessonsCount: 202,
    hour: 14,
    createdAt: "ا اذر 1402",
    teacherName: "دکتر بحرالعلوم",
    teacherJob: "برنامه نویسی تحت فرانت و بکند",
    teacherImage: "/src/assets/images/CourseDetails/Teachers/teacher.png",
    studentsCount: 256,
    price: 5000000,
    courseStatus: "در حال برگزاری",
    courseEndTime: "24 شهریور 1403",
  },
  {
    id: 8,
    image: "/src/assets/images/Landing/LandingCourses/CourseImages/react.jpg",
    title: "دوره جامع React JS صفر تا صد",
    description:
      "محبوب ترین کتابخانه ی جاوااسکریپت حل مساله به روش کدنویسی پیشرفته و تمیز؛ برای مسائل واقعی دنیای نرم افزار  محبوب ترین کتابخانه ی جاوااسکریپت محبوب ترین کتابخانه ی جاوااسکریپت حل مساله به روش کدنویسی پیشرفته و تمیز؛ محبوب ترین کتابخانه ی جاوااسکریپت حل مساله به روش کدنویسی پیشرفته و تمیز.",
    lessonsCount: 202,
    hour: 14,
    createdAt: "ا اذر 1402",
    teacherName: "دکتر بحرالعلوم",
    teacherJob: "برنامه نویسی تحت فرانت و بکند",
    teacherImage: "/src/assets/images/CourseDetails/Teachers/teacher.png",
    studentsCount: 256,
    price: 5000000,
    courseStatus: "در حال برگزاری",
    courseEndTime: "24 شهریور 1403",
  },
  {
    id: 9,
    image: "/src/assets/images/Landing/LandingCourses/CourseImages/html.jpg",
    title: "دوره جامع HTML 5 صفر تا صد",
    description:
      "محبوب ترین کتابخانه ی جاوااسکریپت حل مساله به روش کدنویسی پیشرفته و تمیز؛ برای مسائل واقعی دنیای نرم افزار  محبوب ترین کتابخانه ی جاوااسکریپت محبوب ترین کتابخانه ی جاوااسکریپت حل مساله به روش کدنویسی پیشرفته و تمیز؛ محبوب ترین کتابخانه ی جاوااسکریپت حل مساله به روش کدنویسی پیشرفته و تمیز.",
    lessonsCount: 202,
    hour: 14,
    createdAt: "ا اذر 1402",
    teacherName: "دکتر بحرالعلوم",
    teacherJob: "برنامه نویسی تحت فرانت و بکند",
    teacherImage: "/src/assets/images/CourseDetails/Teachers/teacher.png",
    studentsCount: 256,
    price: 5000000,
    courseStatus: "در حال برگزاری",
    courseEndTime: "24 شهریور 1403",
  },
];
